/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ejemplos_java_SHA1Lib */

#ifndef _Included_ejemplos_java_SHA1Lib
#define _Included_ejemplos_java_SHA1Lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ejemplos_java_SHA1Lib
 * Method:    sha1_hash
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_ejemplos_java_SHA1Lib_sha1_1hash
  (JNIEnv *, jobject, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
